FROM node:16.20.2-alpine AS build
WORKDIR /app
ENV DISABLE_ESLINT_PLUGIN=true

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

FROM nginx:stable-alpine
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
